[versions]
kotlin = "1.9.23"
ktor = "2.3.12"
serialization = "1.6.3"
jsoup = "1.17.2"
dotenv = "6.4.1"
logback = "1.4.14"
jtokkit = "0.6.1"

[libraries]
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
